/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PostData {
  title: string
  content: string
}
export interface Match {
  target: PostData
  score: number
}
export interface FindTopNResult {
  matches: Array<Match>
  processTime: number
}
export declare function findSimilarPostsNative(source: PostData, candidates: Array<PostData>, topN: number): FindTopNResult
export declare function findSimilarPostsNativeParallel(source: PostData, candidates: Array<PostData>, topN: number): FindTopNResult
export declare function findSimilarPostsNativeAsync(source: PostData, candidates: Array<PostData>, topN: number): Promise<FindTopNResult>
export declare class PostStore {
  constructor()
  preload(posts: Array<PostData>): void
  findSimilarPosts(source: PostData, topN: number): Promise<FindTopNResult>
}
