/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DbOptions {
  url: string
  table: string
}
export interface IssueFeatures {
  operation?: string
  phenomenon?: string
  expectedBehavior?: string
  actualBehavior?: string
}
export interface IssueFeaturesRecord {
  issueId: string
  features: IssueFeatures
}
export interface SimilarIssueFeaturesRecord {
  issueId: string
  features: IssueFeatures
  /** Similarity score `0 - 1`, higher is more similar. */
  score: number
}
export declare class IssueFeatureStore {
  static fromCsv(path: string): Promise<IssueFeatureStore>
  toCsv(path: string): Promise<void>
  static fromDb(options: DbOptions): Promise<IssueFeatureStore>
  constructor(records?: Array<IssueFeaturesRecord> | undefined | null)
  setRecord(record: IssueFeaturesRecord): void
  getRecord(issueId: string): IssueFeaturesRecord | null
  removeRecord(issueId: string): boolean
  findSimilarRecords(features: IssueFeatures, topN?: number | undefined | null, signal?: AbortSignal | undefined | null): Promise<Array<SimilarIssueFeaturesRecord>>
}
